// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKvX0OlX8xlwU9PXt_S9d4WcBLi07ia0',
    appId: '1:284030729203:web:4a90999b06e21d5cb17086',
    messagingSenderId: '284030729203',
    projectId: 'cardiowatch-c9ce7',
    authDomain: 'cardiowatch-c9ce7.firebaseapp.com',
    storageBucket: 'cardiowatch-c9ce7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2mWOMuwyJxUpt_9-NHULOeyMgwlxd-r4',
    appId: '1:284030729203:android:df93ac404c8f86b9b17086',
    messagingSenderId: '284030729203',
    projectId: 'cardiowatch-c9ce7',
    storageBucket: 'cardiowatch-c9ce7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd8AYxCnrQuX1IK73Vz-dVMS1uHAaHQcg',
    appId: '1:284030729203:ios:628adccd381b367db17086',
    messagingSenderId: '284030729203',
    projectId: 'cardiowatch-c9ce7',
    storageBucket: 'cardiowatch-c9ce7.appspot.com',
    iosClientId: '284030729203-0k9abq538srdi4jlboeks0rd8ri8701j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardioWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd8AYxCnrQuX1IK73Vz-dVMS1uHAaHQcg',
    appId: '1:284030729203:ios:628adccd381b367db17086',
    messagingSenderId: '284030729203',
    projectId: 'cardiowatch-c9ce7',
    storageBucket: 'cardiowatch-c9ce7.appspot.com',
    iosClientId: '284030729203-0k9abq538srdi4jlboeks0rd8ri8701j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardioWatch',
  );
}
